### ISSUE TITLE
Screenshot of the UI

### ISSUE THREAD

**Issue by bruth** [SimCorp/nats-topology-visualiser#84]
Hi, I was curious if you could share a screenshot of what the visual looks like?

**Comment by pizzaluc** [comment]
Will add the picture to the readme at some point, but here it is for now.

It should be noted this was a collaboration between students at ITU and Simcorp, and sadly ran out of time before it got production ready.

![visualizer](https://user-images.githubusercontent.com/6737028/172728656-44a45ea4-f145-4051-ab9f-5f62af7990e9.PNG)

**Comment by bruth** [comment]
I appreciate it thanks!

> It should be noted this was a collaboration between students at ITU and Simcorp

Great idea
